#!/bin/bash -e
test -x ./node_modules/.bin/qrcode

function fail {
	echo "$*"
	exit 1
}

OUTFILE="out.png"

case "$1" in 
	png) out="-o out.png"
		test -r $OUTFILE && fail "FATAL: output file $OUTFILE already exists"
		 ;;
	console) out="" ;;
	*)	
		echo "usage: $0 [console|png]"
		echo " and then enter access token and passphrase."
		exit 1
		;;
	
esac

echo ""
echo Create Account Provisioning QRCODE:
echo -n "Account Access-Token: "
read token
echo $token | grep ^v2 > /dev/null || fail "FATAL: invalid token"


echo -n "Wallet Passphrase: "
read password


json="{\"token\":\"$token\",\"password\":\"$password\"}"

#merely check input is valid json..
echo a=$json|node >& /dev/null || fail "FATAL: invalid passphrase/token"

npx qrcode $out $json
test -n "$out" && echo "REMEMBER: print and DELETE the generated $OUTFILE"
