#!/bin/bash -e
cd `dirname $0`

KEYSTORE=${KEYSTORE=upload.jks}
ALIAS=upload
UNSIGNED_APK=./app/build/outputs/apk/release/app-release-unsigned.apk 
APK_JSON=./app/build/outputs/apk/release/output.json

test -n "$ANDROID_HOME" || export ANDROID_HOME=~/Library/Android/sdk/

ZIPALIGN=$ANDROID_HOME/build-tools/28.0.3/zipalign
APKSIGNER=$ANDROID_HOME/build-tools/28.0.3/apksigner



function fatal() {
	echo "FATAL: $*"
	exit 1
}

test -x $ZIPALIGN || fatal "unable to find zipalign check ANDROID_HOME ($ANDROID_HOME)"
test -x $APKSIGNER || fatal "unable to find apksigner check ANDROID_HOME ($ANDROID_HOME)"
test -r $KEYSTORE || fatal "Keystore file KEYSTORE=$KEYSTORE not found"

GIT_TAG=`git describe --tags  --dirty`
echo $GIT_TAG|grep -- - && fatal "git is not clean, or not on a tag"

./gradlew assRel

VERSION_NAME=`cat $APK_JSON|perl -ne 'print $1 if /versionName[ ":]+(\S+?)"/'`
outapk=bizpoc-${VERSION_NAME}.apk

test "$GIT_TAG" == "v$VERSION_NAME" || fatal "git tag $GIT_TAG different from versionName: $VERSION_NAME"

test -r $outapk && fatal output $outapk already exist. 

zip -d ./app/build/outputs/apk/release/app-release-unsigned.apk *.version */services/*
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $KEYSTORE $UNSIGNED_APK $ALIAS

$ZIPALIGN -v 4 $UNSIGNED_APK $outapk
$APKSIGNER verify -verbose $outapk

echo
echo "=========================="
echo "== generated: $outapk"
echo '== Create release on: https://play.google.com/apps/publish/?account=6096797255948663962#ManageReleaseTrackPlace:p=com.tabookey.bizpoc&appid=4972085663822317054&releaseTrackId=4700328908680150302'
